site_name: Dotfiles
site_url: https://docs.wwwsnow.org
repo_url: https://github.com/nataliafonseca/dotfiles
repo_name: nataliafonseca/dotfiles

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  font:
    code: JetBrains Mono
  palette:
    primary: deep purple
    accent: deep purple
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

nav:
  - Overview: index.md
  - Operating Systems:
      - Arch Linux: os/arch.md
      - macOS: os/mac.md
      - Ubuntu Server: os/ubuntu-server.md
      - Ubuntu: os/ubuntu.md
  - Shared Guides:
      - Dotfiles: common/dotfiles.md
      - SSH: common/ssh.md
      - Storage: common/storage.md
      - GNOME: common/gnome.md
      - rEFInd: common/refind.md
