site_name: Dotfiles
site_url: https://docs.wwwsnow.org
repo_url: https://github.com/nataliafonseca/dotfiles
repo_name: nataliafonseca/dotfiles
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  font:
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Overview: index.md
  - Operating Systems:
      - Arch Linux: os/arch.md
      - macOS: os/mac.md
      - Ubuntu Server: os/ubuntu-server.md
      - Ubuntu: os/ubuntu.md
  - Shared Guides:
      - Bootstrap: common/bootstrap.md
      - SSH: common/ssh.md
      - Storage: common/storage.md
      - GNOME: common/gnome.md
