#!/usr/bin/env zsh

function vpn_on() {
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 > /dev/null

eval $(op signin)

local OVPN_FILE=$HOME/Nutrien/*.ovpn
local OVPN_USER=$(op item get OneLogin --fields username)
local OVPN_PASSWORD=$(op item get OneLogin --fields password)$(op item get OneLogin --otp)

nohup sudo bash -c 'openvpn --config '"$OVPN_FILE"' --auth-user-pass <(echo -e "'"$OVPN_USER"'\n'"$OVPN_PASSWORD"'")' > /dev/null &
}

function vpn_off() {
sudo killall openvpn
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 > /dev/null
}

while (( $# )); do
  case $1 in
    on|--on) vpn_on && return;;
    off|--off) vpn_off && return;;
  esac
  shift
done
