#!/usr/bin/env zsh

# Check if the URL is provided
if [ -z "$1" ]; then
  echo "Please provide a URL to a font zip file."
  exit 1
fi

echo "Installing font..."

# Create a temporary directory
TEMP_DIR=$(mktemp -d --tmpdir=$XDG_CACHE_HOME)

# Download the font zip file
wget -O "$TEMP_DIR/font.zip" "$1"

# Unzip the font file
unzip "$TEMP_DIR/font.zip" -d "$TEMP_DIR"

# Create user fonts directory if it doesn't exist
mkdir -p $XDG_DATA_HOME/fonts/

# Move the font files to the user fonts directory
sudo mv "$TEMP_DIR"/*.ttf $XDG_DATA_HOME/fonts/
sudo mv "$TEMP_DIR"/*.otf $XDG_DATA_HOME/fonts/

# Update the font cache
fc-cache -f -v

# Clean up
rm -rf "$TEMP_DIR"

echo "Fonts installed successfully!"

