#!/usr/bin/env zsh

# Open/edit quick note

local filename="$(date '+%Y-%m-%d_%H-%M-%S').md"
local editor="$EDITOR"

local usage=(
  "n [-h|--help]"
  "n [-p|--permanote] [-e|--editor=<editor>] [<filename>]"
)

while (( $# )); do
  case $1 in
    -h|--help)          printf "%s\n" $usage && return  ;;
    -e|--editor)        shift; editor=$1                ;;
    -e=*|--editor=*)    editor="${1#*=}"                ;;
    -p|--permanote)     filename="permanote.md"         ;;
    *)                  filename="$@"; break         ;;
  esac
  shift
done

$EDITOR "$QUICK_NOTES_DIR/$filename"
